% generate simulated EEG data with default arguments

% add EEGLAB to path
addpath("/Users/ernie/Dropbox/CODE/eeglab");
eeglab nogui;

% EEG = eeg_htpEegSimulateVep();

% define input arguments
latency1 = 75;
latency2 = 150;
latency3 = 250;
latency4 = 400;

amplitude1 = -.5;
amplitude2 = 1.5;
amplitude3 = .5;
amplitude4 = -1;

baseline = 0;
baseline_duration = 150;
numTrials = 150;
numChannels = 128;
sampleRate = 1000;
trialLength = 1000;
noiseAmplitude = 20;

jitterRange1 = 10;
jitterRange2 = 50;
jitterRange3 = 25;
jitterRange4 = 100;

peak_channel = 75;
variability_factor = .1;

EEGCell = {};

%for i = 1 : 100

% generate simulated EEG data
%EEGCell{i} = 

eeg_htpEegSimulateVep(...
    'latency1', latency1, ...
    'latency2', latency2, ...
    'latency3', latency3, ...
    'latency4', latency4, ...
    'amplitude1', amplitude1, ...
    'amplitude2', amplitude2, ...
    'amplitude3', amplitude3, ...
    'amplitude4', amplitude4, ...
    'baseline', baseline, ...
    'baseline_duration', baseline_duration, ...
    'numTrials', numTrials, ...
    'numChannels', numChannels, ...
    'sampleRate', sampleRate, ...
    'trialLength', trialLength, ...
    'noiseAmplitude', noiseAmplitude, ...
    'jitterRange1', jitterRange1, ...
    'jitterRange2', jitterRange2, ...
    'jitterRange3', jitterRange3, ...
    'jitterRange4', jitterRange4, ...
    'peak_channel', peak_channel, ...
    'variability_factor', variability_factor);
    
%end
